#Numpy

Numpy is a fundamental library for scientific computing in Python. It provides support for arrays and matrices, along with a collection of mathematical functions to operate on these data structures.In this lesson, we will cover the basics of Numpy, focusing on arrays and vectorized operations.

In [14]:
!pip install numpy 

In [15]:
import numpy as np

##create array using numpy
## create a 1D array

arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [16]:
##1D array
arr2= np.array([1,2,3,4,5])
arr2.reshape(1,5)

array([[1, 2, 3, 4, 5]])

In [17]:
arr2=np.array([[1,2,3,4,5]])
arr2.shape

(1, 5)

In [18]:
##2D array
arr2=np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [19]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [20]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [21]:
##identity matrix

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
arr= np.array([[1,2,3],[4,5,6]])

print("Array:\n", arr)
print("Shape:", arr.shape) #output:(2,3)
print("Number of dimensions:", arr.ndim) #output:2
print("Size(number of elements):", arr.size)#output : 6
print("Data type:", arr.dtype)
print("Item size(in bytes):", arr.itemsize)

Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimensions: 2
Size(number of elements): 6
Data type: int64
Item size(in bytes): 8


In [23]:
### Numpy vectorized operations
import numpy as np
arr1= np.array([1,2,3,4,5])
arr2= np.array([10,20,30,40,50])

###Element wise addition
print("addition:", arr1+arr2)

###Element wise subtraction
print("subtraction:", arr1-arr2)


###Element wise multiplication
print("multiplication:", arr1*arr2)

###Element wise division
print("division:", arr1/arr2)



addition: [11 22 33 44 55]
subtraction: [ -9 -18 -27 -36 -45]
multiplication: [ 10  40  90 160 250]
division: [0.1 0.1 0.1 0.1 0.1]


In [24]:
### Universal functions

arr= np.array([2,3,4,5,6])

##square root
print(np.sqrt(arr))

##exponential
print(np.exp(arr))

##sine
print(np.sin(arr))

##natural log
print(np.log(arr))


[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [25]:
## array slicing and indexing

arr= np.array([[1,2,3,4,],[5,6,7,8],[9,10,11,12]])
print("Array :\n" , arr)

Array :
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [26]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [27]:
print(arr[0][0])
print(arr[0:2][1:])

1
[[5 6 7 8]]


In [13]:
print(arr[1:,1:3])

[[ 6  7]
 [10 11]]


In [28]:
##modify 

arr[0,0]=100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [29]:
arr[1:]=100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [30]:
####statistical concept -- Normalization
##to have a mean of 0 and standard deviation of 1

data= np.array ([1,2,3,4,5])

#calculate the mean and standard deviation
mean = np.mean(data)
std_dev= np.std(data)

##normalize the data

normalized_data= (data- mean)/ std_dev
print("Normalized data:", normalized_data)

Normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [31]:
data = np.array([1,2,3,4,5,6,7,8,9,10])

##Mean
mean= np.mean(data)
print("Mean:", mean)

##median
median= np.median(data)
print("Median:", median)

#standard deviation

std_dev = np.std(data)
print("standard deviation:", std_dev)

##variamce 
variance= np.var(data)
print("variance:", variance)

Mean: 5.5
Median: 5.5
standard deviation: 2.8722813232690143
variance: 8.25


In [35]:
##logical operations

data= np.array([1,2,3,4,5,6,7,8,9,10])

data[(data>=5 ) & (data<=8)]

array([5, 6, 7, 8])